# Common properties

spring:
  flyway:
    baseline-on-migrate: true
  profiles:
    active: dev # environment to activate

mybatis:
  configuration:
    # for converting SQL column names (underscore) to POJOs
    map-underscore-to-camel-case: true
jwt:
  key: "brli3"
  expiry-time: 1 # JWT token expiry time in hours