# Dev environment
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/article_net
    username: brli3
    password: password
  data:
    redis:
      port: 16379
      host: localhost

logging:
  level:
    web: debug
    sql: debug
    org:
      mybatis: debug